### ISSUE TITLE
Support for WEBP format

### ISSUE THREAD

**Issue by Ferdari** [GabrielGil/TimThumb#1]
Support for Webp format, as it retrieves error when trying WEBP file format.

WEBP is a new modern image file type that is currently used and required for websites optimizations.
```
The following error(s) occured:

    The image being resized is not a valid gif, jpg or png.
```

**Comment by GabrielGil** [comment]
Hi @Ferdari. TimThumb got end-of-life back in 2014, thus `webp` is and will not be supported.

You can read the reasons here: [Ben Gillbanks: TimThumb is No Longer Supported or Maintained](https://www.binarymoon.co.uk/2014/09/timthumb-end-life)
